### ISSUE TITLE
Versions available in npm do not match released versions

### ISSUE THREAD

**Issue by davidbarhambgch** [martinlindenberg/serverless-plugin-sns#12]
I'm currently running serverless version 0.5.3 and have been getting the following error when using the serverless-plugin-sns when trying to do a function deploy

/home/dbarham/workspace/kairos-migration/kairos-migration/kairos-lambda/kairos-migration/node_modules/serverless-plugin-sns/index.js:6
        SCli       = require(S.getServerlessPath('utils/cli')),
                               ^

TypeError: S.getServerlessPath is not a function

Having seen how plugins worked changed in serverless 0.5 onwards I then checked the version of the sns plugin and have 0.0.10 which doesn't match any of the released versions, after to update to the current latest released version (0.5.3) I was got this from npm

npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.0.6","0.0.7","0.0.8","0.0.9","0.0.10"]

**Comment by martinlindenberg** [comment]
looks strange. to be honestly - i have no idea what to do to reproduce this behaviour.

i checked out serverless 0.5.3 and created a new project with one test function. then i installed the sns plugin with `npm install serverless-plugin-sns` and added the required lines to s-function.json...

it worked out of the box: it deploys, it creates a sns topic and attaches it to the function...

can you please tell me what to do, to reproduce your error ?

**Comment by martinlindenberg** [comment]
two weeks - no response. 
sorry - please reopen if required.
