### ISSUE TITLE
AWS IAM Profile

### ISSUE THREAD

**Issue by AdrienFromToulouse** [martinlindenberg/serverless-plugin-sns#13]
Hey! many thanks for that great plugin.

I am still new to serverless and its plugins but from your point of view, would it be possible for your plugin to use the AWS IAM Role used during the serverless project initialization?

Indeed, by calling the AWS SDK it always take the default one. And this default profile might not be able to perform an `is not authorized to perform: lambda:AddPermission on resource: arn:blah'

I did not read the doc for plugin interface, but I guess it would be possible to fetch the current IAM profile used by the project.

Does it make sense to you or am I wrong?

Cheers!

**Comment by martinlindenberg** [comment]
I think you are mixing two Account types.

The serverless framework uses your local credentials that you've set up with the command `aws configure`. These credentials were attached to an account that needs a lot of permissions to different services to deploy your functions or to create some infrastructure (If i understood correctly, serverless recommends to use an user with administrator access: http://docs.serverless.com/docs/configuring-aws). Serverless itself uses these credentials to create a role, that is used by your lambda functions. 

As your lambda functions were public available and you normally won't grant full access to everyone for all services of your aws account, this role needs to be as restrictive as possible.

Regarding your Question:
During the deployment, serverless uses your local credentials to deploy the functions, to setup some sns topics and to subscribe the lambda to this topic. You have to add the required permissions to the aws account that you're using locally.
