### ISSUE TITLE
Bug: Cant bind multiple lambdas from the same project to the same sns channel

### ISSUE THREAD

**Issue by jayzalowitz** [martinlindenberg/serverless-plugin-sns#15]
So i just created a project with a logging lambda. Built the s-function like:
"sns": {
    "topic": "x"
  },
  "sns": {
    "topic": "y"
  },
  "sns": {
    "topic": "z"
  },
  "sns": {
    "topic": "alpha"
  },

and it only bound to the one that didn't already have a lambda bound to it (alpha)
Redeploying to make sure its not only taking the last one, but this is an issue if you want to bind the same lambda to multiple sns for logging.

**Comment by jayzalowitz** [comment]
Edit: it only takes the latest 1

**Comment by martinlindenberg** [comment]
I've created an update

Please use the following structure to subscribe a lambda to multiple topics

```
  "sns": [
    {"topic": "your-dev-sns-topic1"},
    {"topic": "your-dev-sns-topic2"}
  ]
```
