### ISSUE TITLE
Can not deploy using gulp (or anything other than the command line)

### ISSUE THREAD

**Issue by antonydenyer** [martinlindenberg/serverless-plugin-sns#17]
We've got a load of gulp scripts that we use for deployments. When we deploy something that uses serverless-plugin-sns the deployment fails. From gulp we do:

```
gulp.task('serverless:deploy:functions', () => {
  const options = {}
  return serverless.init().then(() => {
    return serverless.actions.functionDeploy(options)
  })
})

```

To get round the problem we can monkey patch wth:

```
gulp.task('serverless:deploy:functions', () => {
  const options = {}
  serverless.cli = {
    action: 'deploy',
    context: 'function'
  }
  return serverless.init().then(() => {
    return serverless.actions.functionDeploy(options)
  })
})

```

It is being caused by https://github.com/martinlindenberg/serverless-plugin-sns/blob/master/index.js#L65 but I'm not sure how to resolve it.  

Is their a serverless strategy for dealing with command line arguments?

**Comment by martinlindenberg** [comment]
Do you also use another plugin that works with gulp?

As there are already some checks in https://github.com/martinlindenberg/serverless-plugin-sns/blob/master/index.js#L20-L27, i think the lines https://github.com/martinlindenberg/serverless-plugin-sns/blob/master/index.js#L65-L66 can be removed...
