### ISSUE TITLE
ResourceNotFoundException on deploy

### ISSUE THREAD

**Issue by mikedizon** [martinlindenberg/serverless-plugin-sns#19]
Geting this error when deploying. Do I need to add SNS to the s-resources-cf.json?

Serverless: topic foo-sns-bar-dev does not exist. it will be created now  
Serverless: topic created  
Serverless: binding function getCustomerIGLikes to topic foo-sns-bar-dev  

Serverless: topic foo-sns-bar-dev exists.  
Serverless: binding function getCustomerIGLikes to topic foo-sns-bar-dev  
Unhandled rejection ResourceNotFoundException: The resource you requested does not exist.

**Comment by martinlindenberg** [comment]
thanks for your message. 
it was a side effect of the error handling. an expected error should not call the reject method...

new release 0.5.11 solves it
