### ISSUE TITLE
[Feature Request] Handling variables in topic name

### ISSUE THREAD

**Issue by cscetbon** [martinlindenberg/serverless-plugin-sns#2]
Your plugin does not currently handle them and it would be a great enhancement !

**Comment by lpinca** [comment]
:+1:

We use something like `${project}-${stage}-topicName` in CF and it would be great to do the same for this plugin:

```
...
"sns": {
  "topic": "${project}-${stage}-topicName"
},
...
```

Unfortunately this doesn't work out of the box. `sns` [here](https://github.com/martinlindenberg/serverless-plugin-sns/blob/6f02b52678ea6ed3c5f76fc68ac202193f0198c0/index.js#L91) is the original string (`${project}-${stage}-topicName` in this case).

Maybe it's possible to do something like `sns.replace('${stage}', _this.stage);`

**Comment by cscetbon** [comment]
I will ask the serverless team cause I think it would be easier to handle it before calling the plugin. Actually, if plugins can avoid handling variables/templates substitutions that would be the best

**Comment by lpinca** [comment]
Yes that would be the ideal solution. The CORS plugin has a similar issue, see https://github.com/joostfarla/serverless-cors-plugin/issues/9.

**Comment by martinlindenberg** [comment]
great idea. 

i've added this feature to the topic name

useable variables:
${project} 
${stage}
${component} 
${module} 
${function}

**Comment by lpinca** [comment]
Awesome, thank you!
