### ISSUE TITLE
Does this work with serverless > 1.0?

### ISSUE THREAD

**Issue by marcio0** [martinlindenberg/serverless-plugin-sns#21]
The documentation references the old style config, like `sls-function.json`.

Since 1.0 serverless has migrated to a new config format in a single yml file.

Will this plugin still work?

**Comment by martinlindenberg** [comment]
Unfortunately not. It won't work without modifications with serverless >= 1.0.

**Comment by orfin** [comment]
@martinlindenberg do you plan to maintain this plugin anymore and make it compatible with sls >=1.0? We'd be more than happy to be able to use it with our serverless architecture :-)

**Updated:** ok, as from now, SNS are automatically created by serverless framework :-)

**Comment by martinlindenberg** [comment]
@orfin 
i stopped updating the plugins since they are already covered by the default serverless framework.

I'd recommend using my plugins only, if you need to run sls < 1.0
