### ISSUE TITLE
Difference between this and SNS event source

### ISSUE THREAD

**Issue by seanfisher** [martinlindenberg/serverless-plugin-sns#7]
I'm new to the whole serverless ecosystem, and I'm wondering what the difference is between this and [configuring an SNS event source](http://docs.serverless.com/docs/function-configuration) in the `s-function.json`?

Thanks!

**Comment by martinlindenberg** [comment]
Hi Sean, 
i created this plugin for an earlier version of the serverless framework. I think it should still work, but, as there is now native SNS support in serverless, i would not recommend using the plugin.

Technically there should be no difference between the plugin and serverless >= 0.4: both subscribe a lambda function to an SNS topic.

Regards, Martin
